### ISSUE TITLE
introduce dependabot

### ISSUE THREAD

**Issue by hagenstrahl** [hagenstrahl/anna-otto#3]
purpose: to have continuous package updates we want to use Dependabot which helps us with this.

Acceptance Criteria

- [ ] Dependabot is configured
- [ ] one successful run

**Comment by behindadyingstar** [comment]
Can't access settings of project to enable dependabot

![Image](https://github.com/user-attachments/assets/594244f9-853e-4742-aca9-af8ed5be133f)

**Comment by hagenstrahl** [comment]
Try introducing a new file `dependabot.yml` in the `.github` folder with an equivalent configuration like in immergutrocken.
Here is a screenshot of it:

<img width="856" alt="image" src="https://github.com/user-attachments/assets/5025928a-62ee-45f8-930f-d36097bb61b1">
